[phases.setup]
nixPkgs = ['nodejs_20']  # Underscore, not hyphen—matches Nixpkgs naming

[phases.install]
cmds = ['npm ci --omit=dev']  # Prod-only install, skips dev deps

[phases.build]
cmds = ['npm run build']  # Next.js build to .next

[start]
cmd = 'npm start'  # Ensures Next.js server runs on $PORT