[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm ci --omit=dev'  # Prod install only; cache mount auto-applies here
]

[phases.build]
cmds = [
  'npm run build'  # Just compile to .next—no second ci to avoid lock
]

[start]
cmd = 'npm start'  # Serves .next on $PORT